# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ragnar/git/planetoid

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ragnar/git/planetoid

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ragnar/git/planetoid/CMakeFiles /home/ragnar/git/planetoid/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ragnar/git/planetoid/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named EDAN_35_Lab2

# Build rule for target.
EDAN_35_Lab2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EDAN_35_Lab2
.PHONY : EDAN_35_Lab2

# fast build rule for target.
EDAN_35_Lab2/fast:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/build
.PHONY : EDAN_35_Lab2/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f CMakeFiles/glfw.dir/build.make CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

src/Bonobo.o: src/Bonobo.cpp.o
.PHONY : src/Bonobo.o

# target to build an object file
src/Bonobo.cpp.o:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/Bonobo.cpp.o
.PHONY : src/Bonobo.cpp.o

src/Bonobo.i: src/Bonobo.cpp.i
.PHONY : src/Bonobo.i

# target to preprocess a source file
src/Bonobo.cpp.i:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/Bonobo.cpp.i
.PHONY : src/Bonobo.cpp.i

src/Bonobo.s: src/Bonobo.cpp.s
.PHONY : src/Bonobo.s

# target to generate assembly for a file
src/Bonobo.cpp.s:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/Bonobo.cpp.s
.PHONY : src/Bonobo.cpp.s

src/Deferred.o: src/Deferred.cpp.o
.PHONY : src/Deferred.o

# target to build an object file
src/Deferred.cpp.o:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/Deferred.cpp.o
.PHONY : src/Deferred.cpp.o

src/Deferred.i: src/Deferred.cpp.i
.PHONY : src/Deferred.i

# target to preprocess a source file
src/Deferred.cpp.i:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/Deferred.cpp.i
.PHONY : src/Deferred.cpp.i

src/Deferred.s: src/Deferred.cpp.s
.PHONY : src/Deferred.s

# target to generate assembly for a file
src/Deferred.cpp.s:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/Deferred.cpp.s
.PHONY : src/Deferred.cpp.s

src/GLB.o: src/GLB.cpp.o
.PHONY : src/GLB.o

# target to build an object file
src/GLB.cpp.o:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/GLB.cpp.o
.PHONY : src/GLB.cpp.o

src/GLB.i: src/GLB.cpp.i
.PHONY : src/GLB.i

# target to preprocess a source file
src/GLB.cpp.i:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/GLB.cpp.i
.PHONY : src/GLB.cpp.i

src/GLB.s: src/GLB.cpp.s
.PHONY : src/GLB.s

# target to generate assembly for a file
src/GLB.cpp.s:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/GLB.cpp.s
.PHONY : src/GLB.cpp.s

src/GLBdecl.o: src/GLBdecl.cpp.o
.PHONY : src/GLBdecl.o

# target to build an object file
src/GLBdecl.cpp.o:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/GLBdecl.cpp.o
.PHONY : src/GLBdecl.cpp.o

src/GLBdecl.i: src/GLBdecl.cpp.i
.PHONY : src/GLBdecl.i

# target to preprocess a source file
src/GLBdecl.cpp.i:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/GLBdecl.cpp.i
.PHONY : src/GLBdecl.cpp.i

src/GLBdecl.s: src/GLBdecl.cpp.s
.PHONY : src/GLBdecl.s

# target to generate assembly for a file
src/GLBdecl.cpp.s:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/GLBdecl.cpp.s
.PHONY : src/GLBdecl.cpp.s

src/GLStateInspection.o: src/GLStateInspection.cpp.o
.PHONY : src/GLStateInspection.o

# target to build an object file
src/GLStateInspection.cpp.o:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/GLStateInspection.cpp.o
.PHONY : src/GLStateInspection.cpp.o

src/GLStateInspection.i: src/GLStateInspection.cpp.i
.PHONY : src/GLStateInspection.i

# target to preprocess a source file
src/GLStateInspection.cpp.i:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/GLStateInspection.cpp.i
.PHONY : src/GLStateInspection.cpp.i

src/GLStateInspection.s: src/GLStateInspection.cpp.s
.PHONY : src/GLStateInspection.s

# target to generate assembly for a file
src/GLStateInspection.cpp.s:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/GLStateInspection.cpp.s
.PHONY : src/GLStateInspection.cpp.s

src/GLStateInspectionView.o: src/GLStateInspectionView.cpp.o
.PHONY : src/GLStateInspectionView.o

# target to build an object file
src/GLStateInspectionView.cpp.o:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/GLStateInspectionView.cpp.o
.PHONY : src/GLStateInspectionView.cpp.o

src/GLStateInspectionView.i: src/GLStateInspectionView.cpp.i
.PHONY : src/GLStateInspectionView.i

# target to preprocess a source file
src/GLStateInspectionView.cpp.i:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/GLStateInspectionView.cpp.i
.PHONY : src/GLStateInspectionView.cpp.i

src/GLStateInspectionView.s: src/GLStateInspectionView.cpp.s
.PHONY : src/GLStateInspectionView.s

# target to generate assembly for a file
src/GLStateInspectionView.cpp.s:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/GLStateInspectionView.cpp.s
.PHONY : src/GLStateInspectionView.cpp.s

src/InputHandler.o: src/InputHandler.cpp.o
.PHONY : src/InputHandler.o

# target to build an object file
src/InputHandler.cpp.o:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/InputHandler.cpp.o
.PHONY : src/InputHandler.cpp.o

src/InputHandler.i: src/InputHandler.cpp.i
.PHONY : src/InputHandler.i

# target to preprocess a source file
src/InputHandler.cpp.i:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/InputHandler.cpp.i
.PHONY : src/InputHandler.cpp.i

src/InputHandler.s: src/InputHandler.cpp.s
.PHONY : src/InputHandler.s

# target to generate assembly for a file
src/InputHandler.cpp.s:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/InputHandler.cpp.s
.PHONY : src/InputHandler.cpp.s

src/Log.o: src/Log.cpp.o
.PHONY : src/Log.o

# target to build an object file
src/Log.cpp.o:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/Log.cpp.o
.PHONY : src/Log.cpp.o

src/Log.i: src/Log.cpp.i
.PHONY : src/Log.i

# target to preprocess a source file
src/Log.cpp.i:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/Log.cpp.i
.PHONY : src/Log.cpp.i

src/Log.s: src/Log.cpp.s
.PHONY : src/Log.s

# target to generate assembly for a file
src/Log.cpp.s:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/Log.cpp.s
.PHONY : src/Log.cpp.s

src/LogView.o: src/LogView.cpp.o
.PHONY : src/LogView.o

# target to build an object file
src/LogView.cpp.o:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/LogView.cpp.o
.PHONY : src/LogView.cpp.o

src/LogView.i: src/LogView.cpp.i
.PHONY : src/LogView.i

# target to preprocess a source file
src/LogView.cpp.i:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/LogView.cpp.i
.PHONY : src/LogView.cpp.i

src/LogView.s: src/LogView.cpp.s
.PHONY : src/LogView.s

# target to generate assembly for a file
src/LogView.cpp.s:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/LogView.cpp.s
.PHONY : src/LogView.cpp.s

src/Main.o: src/Main.cpp.o
.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i
.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s
.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/Misc.o: src/Misc.cpp.o
.PHONY : src/Misc.o

# target to build an object file
src/Misc.cpp.o:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/Misc.cpp.o
.PHONY : src/Misc.cpp.o

src/Misc.i: src/Misc.cpp.i
.PHONY : src/Misc.i

# target to preprocess a source file
src/Misc.cpp.i:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/Misc.cpp.i
.PHONY : src/Misc.cpp.i

src/Misc.s: src/Misc.cpp.s
.PHONY : src/Misc.s

# target to generate assembly for a file
src/Misc.cpp.s:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/Misc.cpp.s
.PHONY : src/Misc.cpp.s

src/ObjReader.o: src/ObjReader.cpp.o
.PHONY : src/ObjReader.o

# target to build an object file
src/ObjReader.cpp.o:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/ObjReader.cpp.o
.PHONY : src/ObjReader.cpp.o

src/ObjReader.i: src/ObjReader.cpp.i
.PHONY : src/ObjReader.i

# target to preprocess a source file
src/ObjReader.cpp.i:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/ObjReader.cpp.i
.PHONY : src/ObjReader.cpp.i

src/ObjReader.s: src/ObjReader.cpp.s
.PHONY : src/ObjReader.s

# target to generate assembly for a file
src/ObjReader.cpp.s:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/ObjReader.cpp.s
.PHONY : src/ObjReader.cpp.s

src/Profiler.o: src/Profiler.cpp.o
.PHONY : src/Profiler.o

# target to build an object file
src/Profiler.cpp.o:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/Profiler.cpp.o
.PHONY : src/Profiler.cpp.o

src/Profiler.i: src/Profiler.cpp.i
.PHONY : src/Profiler.i

# target to preprocess a source file
src/Profiler.cpp.i:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/Profiler.cpp.i
.PHONY : src/Profiler.cpp.i

src/Profiler.s: src/Profiler.cpp.s
.PHONY : src/Profiler.s

# target to generate assembly for a file
src/Profiler.cpp.s:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/Profiler.cpp.s
.PHONY : src/Profiler.cpp.s

src/ProfilerView.o: src/ProfilerView.cpp.o
.PHONY : src/ProfilerView.o

# target to build an object file
src/ProfilerView.cpp.o:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/ProfilerView.cpp.o
.PHONY : src/ProfilerView.cpp.o

src/ProfilerView.i: src/ProfilerView.cpp.i
.PHONY : src/ProfilerView.i

# target to preprocess a source file
src/ProfilerView.cpp.i:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/ProfilerView.cpp.i
.PHONY : src/ProfilerView.cpp.i

src/ProfilerView.s: src/ProfilerView.cpp.s
.PHONY : src/ProfilerView.s

# target to generate assembly for a file
src/ProfilerView.cpp.s:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/ProfilerView.cpp.s
.PHONY : src/ProfilerView.cpp.s

src/RenderState.o: src/RenderState.cpp.o
.PHONY : src/RenderState.o

# target to build an object file
src/RenderState.cpp.o:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/RenderState.cpp.o
.PHONY : src/RenderState.cpp.o

src/RenderState.i: src/RenderState.cpp.i
.PHONY : src/RenderState.i

# target to preprocess a source file
src/RenderState.cpp.i:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/RenderState.cpp.i
.PHONY : src/RenderState.cpp.i

src/RenderState.s: src/RenderState.cpp.s
.PHONY : src/RenderState.s

# target to generate assembly for a file
src/RenderState.cpp.s:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/RenderState.cpp.s
.PHONY : src/RenderState.cpp.s

src/SimpleDraw.o: src/SimpleDraw.cpp.o
.PHONY : src/SimpleDraw.o

# target to build an object file
src/SimpleDraw.cpp.o:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/SimpleDraw.cpp.o
.PHONY : src/SimpleDraw.cpp.o

src/SimpleDraw.i: src/SimpleDraw.cpp.i
.PHONY : src/SimpleDraw.i

# target to preprocess a source file
src/SimpleDraw.cpp.i:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/SimpleDraw.cpp.i
.PHONY : src/SimpleDraw.cpp.i

src/SimpleDraw.s: src/SimpleDraw.cpp.s
.PHONY : src/SimpleDraw.s

# target to generate assembly for a file
src/SimpleDraw.cpp.s:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/SimpleDraw.cpp.s
.PHONY : src/SimpleDraw.cpp.s

src/SimpleText.o: src/SimpleText.cpp.o
.PHONY : src/SimpleText.o

# target to build an object file
src/SimpleText.cpp.o:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/SimpleText.cpp.o
.PHONY : src/SimpleText.cpp.o

src/SimpleText.i: src/SimpleText.cpp.i
.PHONY : src/SimpleText.i

# target to preprocess a source file
src/SimpleText.cpp.i:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/SimpleText.cpp.i
.PHONY : src/SimpleText.cpp.i

src/SimpleText.s: src/SimpleText.cpp.s
.PHONY : src/SimpleText.s

# target to generate assembly for a file
src/SimpleText.cpp.s:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/SimpleText.cpp.s
.PHONY : src/SimpleText.cpp.s

src/StructDesc.o: src/StructDesc.cpp.o
.PHONY : src/StructDesc.o

# target to build an object file
src/StructDesc.cpp.o:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/StructDesc.cpp.o
.PHONY : src/StructDesc.cpp.o

src/StructDesc.i: src/StructDesc.cpp.i
.PHONY : src/StructDesc.i

# target to preprocess a source file
src/StructDesc.cpp.i:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/StructDesc.cpp.i
.PHONY : src/StructDesc.cpp.i

src/StructDesc.s: src/StructDesc.cpp.s
.PHONY : src/StructDesc.s

# target to generate assembly for a file
src/StructDesc.cpp.s:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/StructDesc.cpp.s
.PHONY : src/StructDesc.cpp.s

src/Types.o: src/Types.cpp.o
.PHONY : src/Types.o

# target to build an object file
src/Types.cpp.o:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/Types.cpp.o
.PHONY : src/Types.cpp.o

src/Types.i: src/Types.cpp.i
.PHONY : src/Types.i

# target to preprocess a source file
src/Types.cpp.i:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/Types.cpp.i
.PHONY : src/Types.cpp.i

src/Types.s: src/Types.cpp.s
.PHONY : src/Types.s

# target to generate assembly for a file
src/Types.cpp.s:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/Types.cpp.s
.PHONY : src/Types.cpp.s

src/VectorMath.o: src/VectorMath.cpp.o
.PHONY : src/VectorMath.o

# target to build an object file
src/VectorMath.cpp.o:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/VectorMath.cpp.o
.PHONY : src/VectorMath.cpp.o

src/VectorMath.i: src/VectorMath.cpp.i
.PHONY : src/VectorMath.i

# target to preprocess a source file
src/VectorMath.cpp.i:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/VectorMath.cpp.i
.PHONY : src/VectorMath.cpp.i

src/VectorMath.s: src/VectorMath.cpp.s
.PHONY : src/VectorMath.s

# target to generate assembly for a file
src/VectorMath.cpp.s:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/VectorMath.cpp.s
.PHONY : src/VectorMath.cpp.s

src/Window.o: src/Window.cpp.o
.PHONY : src/Window.o

# target to build an object file
src/Window.cpp.o:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/Window.cpp.o
.PHONY : src/Window.cpp.o

src/Window.i: src/Window.cpp.i
.PHONY : src/Window.i

# target to preprocess a source file
src/Window.cpp.i:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/Window.cpp.i
.PHONY : src/Window.cpp.i

src/Window.s: src/Window.cpp.s
.PHONY : src/Window.s

# target to generate assembly for a file
src/Window.cpp.s:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/Window.cpp.s
.PHONY : src/Window.cpp.s

src/gl3w.o: src/gl3w.cpp.o
.PHONY : src/gl3w.o

# target to build an object file
src/gl3w.cpp.o:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/gl3w.cpp.o
.PHONY : src/gl3w.cpp.o

src/gl3w.i: src/gl3w.cpp.i
.PHONY : src/gl3w.i

# target to preprocess a source file
src/gl3w.cpp.i:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/gl3w.cpp.i
.PHONY : src/gl3w.cpp.i

src/gl3w.s: src/gl3w.cpp.s
.PHONY : src/gl3w.s

# target to generate assembly for a file
src/gl3w.cpp.s:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/gl3w.cpp.s
.PHONY : src/gl3w.cpp.s

src/imgui_impl_glfw_gl3.o: src/imgui_impl_glfw_gl3.cpp.o
.PHONY : src/imgui_impl_glfw_gl3.o

# target to build an object file
src/imgui_impl_glfw_gl3.cpp.o:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/imgui_impl_glfw_gl3.cpp.o
.PHONY : src/imgui_impl_glfw_gl3.cpp.o

src/imgui_impl_glfw_gl3.i: src/imgui_impl_glfw_gl3.cpp.i
.PHONY : src/imgui_impl_glfw_gl3.i

# target to preprocess a source file
src/imgui_impl_glfw_gl3.cpp.i:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/imgui_impl_glfw_gl3.cpp.i
.PHONY : src/imgui_impl_glfw_gl3.cpp.i

src/imgui_impl_glfw_gl3.s: src/imgui_impl_glfw_gl3.cpp.s
.PHONY : src/imgui_impl_glfw_gl3.s

# target to generate assembly for a file
src/imgui_impl_glfw_gl3.cpp.s:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/imgui_impl_glfw_gl3.cpp.s
.PHONY : src/imgui_impl_glfw_gl3.cpp.s

src/lodepng.o: src/lodepng.cpp.o
.PHONY : src/lodepng.o

# target to build an object file
src/lodepng.cpp.o:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/lodepng.cpp.o
.PHONY : src/lodepng.cpp.o

src/lodepng.i: src/lodepng.cpp.i
.PHONY : src/lodepng.i

# target to preprocess a source file
src/lodepng.cpp.i:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/lodepng.cpp.i
.PHONY : src/lodepng.cpp.i

src/lodepng.s: src/lodepng.cpp.s
.PHONY : src/lodepng.s

# target to generate assembly for a file
src/lodepng.cpp.s:
	$(MAKE) -f CMakeFiles/EDAN_35_Lab2.dir/build.make CMakeFiles/EDAN_35_Lab2.dir/src/lodepng.cpp.s
.PHONY : src/lodepng.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... EDAN_35_Lab2"
	@echo "... edit_cache"
	@echo "... glfw"
	@echo "... imgui"
	@echo "... rebuild_cache"
	@echo "... src/Bonobo.o"
	@echo "... src/Bonobo.i"
	@echo "... src/Bonobo.s"
	@echo "... src/Deferred.o"
	@echo "... src/Deferred.i"
	@echo "... src/Deferred.s"
	@echo "... src/GLB.o"
	@echo "... src/GLB.i"
	@echo "... src/GLB.s"
	@echo "... src/GLBdecl.o"
	@echo "... src/GLBdecl.i"
	@echo "... src/GLBdecl.s"
	@echo "... src/GLStateInspection.o"
	@echo "... src/GLStateInspection.i"
	@echo "... src/GLStateInspection.s"
	@echo "... src/GLStateInspectionView.o"
	@echo "... src/GLStateInspectionView.i"
	@echo "... src/GLStateInspectionView.s"
	@echo "... src/InputHandler.o"
	@echo "... src/InputHandler.i"
	@echo "... src/InputHandler.s"
	@echo "... src/Log.o"
	@echo "... src/Log.i"
	@echo "... src/Log.s"
	@echo "... src/LogView.o"
	@echo "... src/LogView.i"
	@echo "... src/LogView.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/Misc.o"
	@echo "... src/Misc.i"
	@echo "... src/Misc.s"
	@echo "... src/ObjReader.o"
	@echo "... src/ObjReader.i"
	@echo "... src/ObjReader.s"
	@echo "... src/Profiler.o"
	@echo "... src/Profiler.i"
	@echo "... src/Profiler.s"
	@echo "... src/ProfilerView.o"
	@echo "... src/ProfilerView.i"
	@echo "... src/ProfilerView.s"
	@echo "... src/RenderState.o"
	@echo "... src/RenderState.i"
	@echo "... src/RenderState.s"
	@echo "... src/SimpleDraw.o"
	@echo "... src/SimpleDraw.i"
	@echo "... src/SimpleDraw.s"
	@echo "... src/SimpleText.o"
	@echo "... src/SimpleText.i"
	@echo "... src/SimpleText.s"
	@echo "... src/StructDesc.o"
	@echo "... src/StructDesc.i"
	@echo "... src/StructDesc.s"
	@echo "... src/Types.o"
	@echo "... src/Types.i"
	@echo "... src/Types.s"
	@echo "... src/VectorMath.o"
	@echo "... src/VectorMath.i"
	@echo "... src/VectorMath.s"
	@echo "... src/Window.o"
	@echo "... src/Window.i"
	@echo "... src/Window.s"
	@echo "... src/gl3w.o"
	@echo "... src/gl3w.i"
	@echo "... src/gl3w.s"
	@echo "... src/imgui_impl_glfw_gl3.o"
	@echo "... src/imgui_impl_glfw_gl3.i"
	@echo "... src/imgui_impl_glfw_gl3.s"
	@echo "... src/lodepng.o"
	@echo "... src/lodepng.i"
	@echo "... src/lodepng.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

